### ISSUE TITLE
The home directory of the student when opening the terminal is /home/ubuntu, and not the /home/<username>.

### ISSUE THREAD

**Issue by ipeirotis** [ipeirotis/docker#17]
The home directory of the student when opening the terminal is /home/ubuntu, and not the /home/<username>.

**Comment by abenetopoulos** [comment]
This was addressed in 029df28. The user's home directory is set to `/home/${JUPYTERHUB_USER}` on the Kubernetes version, and `/home/ubuntu` on the local version, as that is the image user.
