### ISSUE TITLE
JUPYTERHUB_USER in local-su

### ISSUE THREAD

**Issue by ipeirotis** [ipeirotis/docker#27]
I see that the JUPYTERHUB_USER is not defined when deploying on Google Cloud, which is causing a problem (the container is marked as "restarting" all the time)

https://github.com/ipeirotis/docker/blob/d53c33b93a60ef1f95a9a7df33341f032d08b33d/class-tools-infrastructure/docker/local-su/start-notebook.sh#L15

**Comment by abenetopoulos** [comment]
This was addressed in 029df28.

**Comment by ipeirotis** [comment]
Yep, it is working now.
